spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.31.159.26:5432/conflict_tracker
    username: ferran
    password: ferran

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
